/**
 * Allowlist of cities for programmatic SEO pages.
 *
 * Every entry here unlocks a fan of routes:
 *
 *   /{slug}-3-day-itinerary    (and 2, 4, 5, 7)
 *   /things-to-do-in-{slug}
 *
 * The allowlist gates this — without it, anyone could request
 * `/blahblah-9-day-itinerary` and we'd 200 a thin page with no
 * inventory, which is the textbook way to get a manual spam penalty
 * from Google.
 *
 * Slugs are lowercase kebab-case and stable. Names are display-form.
 * Country names are spelled out (used in headlines + JSON-LD).
 *
 * Add cities here as we get content / inventory coverage. Each line
 * unlocks 6 indexable URLs.
 */

export interface SeoCity {
  /** URL slug. Lowercase, hyphenated, ASCII-safe. */
  slug: string;
  /** Display name ("Tokyo"). */
  name: string;
  /** Free-text country name ("Japan"). */
  countryName: string;
  /** ISO-3166-1 alpha-2. */
  countryCode: string;
  /** Continent or sub-region tag — used to cluster the SEO footer. */
  region: 'asia' | 'europe' | 'americas' | 'mena' | 'oceania' | 'africa';
  /** Approximate centroid. Used for schema.org GeoCoordinates. */
  coordinates: { lat: number; lng: number };
  /**
   * One-line editorial pitch used in the hero + OG description. ≤140
   * chars, no banned voice words.
   */
  oneLiner: string;
  /**
   * Viator-aligned query that returns the best inventory volume for
   * this city. Usually just the city name; some cities work better
   * with country or region appended.
   */
  viatorQuery: string;
}

export const SEO_CITIES: readonly SeoCity[] = [
  // Asia
  {
    slug: 'tokyo',
    name: 'Tokyo',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    oneLiner: 'Mornings at the market, afternoons in the alleys, nights at the bar.',
    viatorQuery: 'Tokyo',
  },
  {
    slug: 'kyoto',
    name: 'Kyoto',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    oneLiner: 'Temple courtyards at dawn, tea houses in the rain, gardens that don’t hurry.',
    viatorQuery: 'Kyoto',
  },
  {
    slug: 'osaka',
    name: 'Osaka',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 34.6937, lng: 135.5023 },
    oneLiner: 'Street food after dark, neon under the bridges, the loudest welcome in Japan.',
    viatorQuery: 'Osaka',
  },
  {
    slug: 'seoul',
    name: 'Seoul',
    countryName: 'South Korea',
    countryCode: 'KR',
    region: 'asia',
    coordinates: { lat: 37.5665, lng: 126.978 },
    oneLiner: 'Palaces, bibimbap, late-night pojangmacha tables; a city that doesn’t sleep early.',
    viatorQuery: 'Seoul',
  },
  {
    slug: 'bangkok',
    name: 'Bangkok',
    countryName: 'Thailand',
    countryCode: 'TH',
    region: 'asia',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    oneLiner: 'River taxis, market kitchens, gilded rooftops; the most generous city on the river.',
    viatorQuery: 'Bangkok',
  },
  {
    slug: 'singapore',
    name: 'Singapore',
    countryName: 'Singapore',
    countryCode: 'SG',
    region: 'asia',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    oneLiner: 'Hawker stalls, garden cities, harbour skyline; everything works, deliciously.',
    viatorQuery: 'Singapore',
  },
  {
    slug: 'bali',
    name: 'Bali',
    countryName: 'Indonesia',
    countryCode: 'ID',
    region: 'asia',
    coordinates: { lat: -8.3405, lng: 115.092 },
    oneLiner: 'Rice terraces, surf at sunrise, temples that smell of frangipani.',
    viatorQuery: 'Bali',
  },
  {
    slug: 'hong-kong',
    name: 'Hong Kong',
    countryName: 'Hong Kong',
    countryCode: 'HK',
    region: 'asia',
    coordinates: { lat: 22.3193, lng: 114.1694 },
    oneLiner: 'Cable car peaks, dim sum at noon, harbour ferries that never stop.',
    viatorQuery: 'Hong Kong',
  },
  {
    slug: 'hanoi',
    name: 'Hanoi',
    countryName: 'Vietnam',
    countryCode: 'VN',
    region: 'asia',
    coordinates: { lat: 21.0285, lng: 105.8542 },
    oneLiner: 'Pho stalls, lake walks, motorbike rivers, the loudest old quarter in Asia.',
    viatorQuery: 'Hanoi',
  },
  {
    slug: 'ho-chi-minh-city',
    name: 'Ho Chi Minh City',
    countryName: 'Vietnam',
    countryCode: 'VN',
    region: 'asia',
    coordinates: { lat: 10.8231, lng: 106.6297 },
    oneLiner: 'Banh mi mornings, rooftop bars at dusk, a city that runs on caffeine and scooters.',
    viatorQuery: 'Ho Chi Minh City',
  },
  {
    slug: 'hoi-an',
    name: 'Hoi An',
    countryName: 'Vietnam',
    countryCode: 'VN',
    region: 'asia',
    coordinates: { lat: 15.8801, lng: 108.338 },
    oneLiner: 'Lantern-lit old town, tailor shops by the river, beach mornings on the coast.',
    viatorQuery: 'Hoi An',
  },
  {
    slug: 'phuket',
    name: 'Phuket',
    countryName: 'Thailand',
    countryCode: 'TH',
    region: 'asia',
    coordinates: { lat: 7.8804, lng: 98.3923 },
    oneLiner: 'Long-tail boat days, viewpoint sunsets, beachfront kitchens that never close.',
    viatorQuery: 'Phuket',
  },
  {
    slug: 'chiang-mai',
    name: 'Chiang Mai',
    countryName: 'Thailand',
    countryCode: 'TH',
    region: 'asia',
    coordinates: { lat: 18.7883, lng: 98.9853 },
    oneLiner: 'Temple mornings, jungle waterfalls, cooking classes that go all afternoon.',
    viatorQuery: 'Chiang Mai',
  },
  {
    slug: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    countryName: 'Malaysia',
    countryCode: 'MY',
    region: 'asia',
    coordinates: { lat: 3.139, lng: 101.6869 },
    oneLiner: 'Twin tower skyline, hawker centres at midnight, jungle parks inside the city.',
    viatorQuery: 'Kuala Lumpur',
  },
  {
    slug: 'manila',
    name: 'Manila',
    countryName: 'Philippines',
    countryCode: 'PH',
    region: 'asia',
    coordinates: { lat: 14.5995, lng: 120.9842 },
    oneLiner: 'Bay sunsets, jeepney rides, a city that opens its kitchens to strangers.',
    viatorQuery: 'Manila',
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    oneLiner: 'Pink palaces, fort ramparts, bazaars that hum with marigolds and spice.',
    viatorQuery: 'Jaipur',
  },
  {
    slug: 'delhi',
    name: 'Delhi',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 28.6139, lng: 77.209 },
    oneLiner: 'Mughal monuments, food lanes, a capital that never narrates itself quietly.',
    viatorQuery: 'Delhi',
  },
  {
    slug: 'mumbai',
    name: 'Mumbai',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 19.076, lng: 72.8777 },
    oneLiner: 'Sea-link drives, vada pav at the gate, the city that wrote modern Indian style.',
    viatorQuery: 'Mumbai',
  },
  {
    slug: 'taipei',
    name: 'Taipei',
    countryName: 'Taiwan',
    countryCode: 'TW',
    region: 'asia',
    coordinates: { lat: 25.033, lng: 121.5654 },
    oneLiner: 'Night markets, soup dumplings, mountain hot springs at the city edge.',
    viatorQuery: 'Taipei',
  },
  {
    slug: 'siem-reap',
    name: 'Siem Reap',
    countryName: 'Cambodia',
    countryCode: 'KH',
    region: 'asia',
    coordinates: { lat: 13.3633, lng: 103.8564 },
    oneLiner: 'Angkor sunrises, jungle temples, riverside bars after a long temple day.',
    viatorQuery: 'Siem Reap',
  },
  {
    slug: 'da-nang',
    name: 'Da Nang',
    countryName: 'Vietnam',
    countryCode: 'VN',
    region: 'asia',
    coordinates: { lat: 16.0544, lng: 108.2022 },
    oneLiner: 'Long beaches, marble mountains, Hoi An a half hour south, mountain passes north.',
    viatorQuery: 'Da Nang',
  },
  {
    slug: 'sapporo',
    name: 'Sapporo',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 43.0618, lng: 141.3545 },
    oneLiner: 'Snow festival winters, ramen alleys, mountain onsen rides at the city edge.',
    viatorQuery: 'Sapporo',
  },
  {
    slug: 'penang',
    name: 'Penang',
    countryName: 'Malaysia',
    countryCode: 'MY',
    region: 'asia',
    coordinates: { lat: 5.4141, lng: 100.3288 },
    oneLiner: 'Heritage shophouses, hawker centres, beach hills, the unofficial food capital of Asia.',
    viatorQuery: 'Penang',
  },
  {
    slug: 'yogyakarta',
    name: 'Yogyakarta',
    countryName: 'Indonesia',
    countryCode: 'ID',
    region: 'asia',
    coordinates: { lat: -7.7956, lng: 110.3695 },
    oneLiner: 'Borobudur sunrises, batik workshops, Javanese palaces, volcanoes on the horizon.',
    viatorQuery: 'Yogyakarta',
  },
  {
    slug: 'boracay',
    name: 'Boracay',
    countryName: 'Philippines',
    countryCode: 'PH',
    region: 'asia',
    coordinates: { lat: 11.9674, lng: 121.9248 },
    oneLiner: 'Powder-sand beaches, paraw sails at sunset, island-hopping mornings.',
    viatorQuery: 'Boracay',
  },
  {
    slug: 'beijing',
    name: 'Beijing',
    countryName: 'China',
    countryCode: 'CN',
    region: 'asia',
    coordinates: { lat: 39.9042, lng: 116.4074 },
    oneLiner: 'Forbidden City mornings, Great Wall day trips, hutong evenings under red lanterns.',
    viatorQuery: 'Beijing',
  },
  {
    slug: 'shanghai',
    name: 'Shanghai',
    countryName: 'China',
    countryCode: 'CN',
    region: 'asia',
    coordinates: { lat: 31.2304, lng: 121.4737 },
    oneLiner: 'Bund skyline at night, dumpling houses at noon, lane neighborhoods that feel a century back.',
    viatorQuery: 'Shanghai',
  },
  {
    slug: 'krabi',
    name: 'Krabi',
    countryName: 'Thailand',
    countryCode: 'TH',
    region: 'asia',
    coordinates: { lat: 8.0863, lng: 98.9063 },
    oneLiner: 'Limestone cliffs over emerald water, longtail boat days to Phi Phi and beyond.',
    viatorQuery: 'Krabi',
  },
  {
    slug: 'maldives',
    name: 'Maldives',
    countryName: 'Maldives',
    countryCode: 'MV',
    region: 'asia',
    coordinates: { lat: 3.2028, lng: 73.2207 },
    oneLiner: 'Overwater villas, reef snorkels, sandbanks at low tide, the slowest pace in the Indian Ocean.',
    viatorQuery: 'Maldives',
  },
  {
    slug: 'colombo',
    name: 'Colombo',
    countryName: 'Sri Lanka',
    countryCode: 'LK',
    region: 'asia',
    coordinates: { lat: 6.9271, lng: 79.8612 },
    oneLiner: 'Hopper breakfasts, tuktuk markets, ocean promenades, the start of every Sri Lanka loop.',
    viatorQuery: 'Colombo',
  },
  {
    slug: 'kathmandu',
    name: 'Kathmandu',
    countryName: 'Nepal',
    countryCode: 'NP',
    region: 'asia',
    coordinates: { lat: 27.7172, lng: 85.324 },
    oneLiner: 'Himalayan trek starts, temple courtyards, momo dinners under prayer flags.',
    viatorQuery: 'Kathmandu',
  },
  {
    slug: 'pattaya',
    name: 'Pattaya',
    countryName: 'Thailand',
    countryCode: 'TH',
    region: 'asia',
    coordinates: { lat: 12.9236, lng: 100.8825 },
    oneLiner: 'Beach resorts, island ferries to Koh Larn, nightlife strips with a sunrise side.',
    viatorQuery: 'Pattaya',
  },
  {
    slug: 'luang-prabang',
    name: 'Luang Prabang',
    countryName: 'Laos',
    countryCode: 'LA',
    region: 'asia',
    coordinates: { lat: 19.8845, lng: 102.1348 },
    oneLiner: 'UNESCO Buddhist town, dawn alms-giving, Mekong sunsets, waterfalls in the jungle.',
    viatorQuery: 'Luang Prabang',
  },
  {
    slug: 'agra',
    name: 'Agra',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 27.1767, lng: 78.0081 },
    oneLiner: 'Taj Mahal at sunrise, marble inlay workshops, Mughal forts above the Yamuna.',
    viatorQuery: 'Agra',
  },
  {
    slug: 'goa',
    name: 'Goa',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 15.2993, lng: 74.124 },
    oneLiner: 'Beach shacks, Portuguese churches, scooter days between the north and south coves.',
    viatorQuery: 'Goa',
  },
  {
    slug: 'hue',
    name: 'Hue',
    countryName: 'Vietnam',
    countryCode: 'VN',
    region: 'asia',
    coordinates: { lat: 16.4637, lng: 107.5909 },
    oneLiner: 'Imperial citadel, royal tombs along the Perfume River, central Vietnam’s richest food capital.',
    viatorQuery: 'Hue Vietnam',
  },
  {
    slug: 'busan',
    name: 'Busan',
    countryName: 'South Korea',
    countryCode: 'KR',
    region: 'asia',
    coordinates: { lat: 35.1796, lng: 129.0756 },
    oneLiner: 'Hillside fishing villages, fresh-cut sashimi at Jagalchi, sunrise beaches at Haeundae.',
    viatorQuery: 'Busan',
  },
  {
    slug: 'hiroshima',
    name: 'Hiroshima',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 34.3853, lng: 132.4553 },
    oneLiner: 'Peace Park mornings, okonomiyaki nights, the Miyajima torii at high tide.',
    viatorQuery: 'Hiroshima',
  },

  // Europe
  {
    slug: 'paris',
    name: 'Paris',
    countryName: 'France',
    countryCode: 'FR',
    region: 'europe',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    oneLiner: 'Long lunches, late museums, evening light on the river.',
    viatorQuery: 'Paris',
  },
  {
    slug: 'rome',
    name: 'Rome',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    oneLiner: 'Pasta at midnight, Vatican mornings, ruins around every corner.',
    viatorQuery: 'Rome',
  },
  {
    slug: 'london',
    name: 'London',
    countryName: 'United Kingdom',
    countryCode: 'GB',
    region: 'europe',
    coordinates: { lat: 51.5072, lng: -0.1276 },
    oneLiner: 'Markets in the morning, theatre at night, pubs in between.',
    viatorQuery: 'London',
  },
  {
    slug: 'barcelona',
    name: 'Barcelona',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 41.3851, lng: 2.1734 },
    oneLiner: 'Gaudí mornings, beach afternoons, late dinners that don’t end before midnight.',
    viatorQuery: 'Barcelona',
  },
  {
    slug: 'lisbon',
    name: 'Lisbon',
    countryName: 'Portugal',
    countryCode: 'PT',
    region: 'europe',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    oneLiner: 'Funicular hills, fado tables, golden light on the Tagus.',
    viatorQuery: 'Lisbon',
  },
  {
    slug: 'amsterdam',
    name: 'Amsterdam',
    countryName: 'Netherlands',
    countryCode: 'NL',
    region: 'europe',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    oneLiner: 'Bicycle pace, canal light, museums you can stay all afternoon in.',
    viatorQuery: 'Amsterdam',
  },
  {
    slug: 'reykjavik',
    name: 'Reykjavík',
    countryName: 'Iceland',
    countryCode: 'IS',
    region: 'europe',
    coordinates: { lat: 64.1466, lng: -21.9426 },
    oneLiner: 'Glacier hikes, hot springs, Northern Lights on cold nights.',
    viatorQuery: 'Reykjavik',
  },
  {
    slug: 'santorini',
    name: 'Santorini',
    countryName: 'Greece',
    countryCode: 'GR',
    region: 'europe',
    coordinates: { lat: 36.3932, lng: 25.4615 },
    oneLiner: 'Caldera walks, sunset cruises, white villages above the wine-dark sea.',
    viatorQuery: 'Santorini',
  },
  {
    slug: 'florence',
    name: 'Florence',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 43.7696, lng: 11.2558 },
    oneLiner: 'Uffizi mornings, Tuscan lunches, Ponte Vecchio at dusk.',
    viatorQuery: 'Florence',
  },
  {
    slug: 'venice',
    name: 'Venice',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 45.4408, lng: 12.3155 },
    oneLiner: 'Canals at dawn, Cicchetti at lunch, fewer crowds than you fear.',
    viatorQuery: 'Venice',
  },
  {
    slug: 'cappadocia',
    name: 'Cappadocia',
    countryName: 'Türkiye',
    countryCode: 'TR',
    region: 'europe',
    coordinates: { lat: 38.6431, lng: 34.8289 },
    oneLiner: 'Balloons at sunrise, cave hotels, pottery towns under fairy chimneys.',
    viatorQuery: 'Cappadocia',
  },
  {
    slug: 'istanbul',
    name: 'Istanbul',
    countryName: 'Türkiye',
    countryCode: 'TR',
    region: 'europe',
    coordinates: { lat: 41.0082, lng: 28.9784 },
    oneLiner: 'Bazaar mornings, Bosphorus afternoons, mosque domes against the dusk.',
    viatorQuery: 'Istanbul',
  },
  {
    slug: 'athens',
    name: 'Athens',
    countryName: 'Greece',
    countryCode: 'GR',
    region: 'europe',
    coordinates: { lat: 37.9838, lng: 23.7275 },
    oneLiner: 'Acropolis at dawn, taverna tables until late, neighborhoods you walk in circles around.',
    viatorQuery: 'Athens',
  },
  {
    slug: 'madrid',
    name: 'Madrid',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    oneLiner: 'Prado mornings, tapas crawls, late dinners that turn into longer nights.',
    viatorQuery: 'Madrid',
  },
  {
    slug: 'seville',
    name: 'Seville',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 37.3891, lng: -5.9845 },
    oneLiner: 'Flamenco patios, alcazar gardens, orange trees on every street.',
    viatorQuery: 'Seville',
  },
  {
    slug: 'berlin',
    name: 'Berlin',
    countryName: 'Germany',
    countryCode: 'DE',
    region: 'europe',
    coordinates: { lat: 52.52, lng: 13.405 },
    oneLiner: 'Wall walks, museum island, beer gardens that stay open as long as the light holds.',
    viatorQuery: 'Berlin',
  },
  {
    slug: 'munich',
    name: 'Munich',
    countryName: 'Germany',
    countryCode: 'DE',
    region: 'europe',
    coordinates: { lat: 48.1351, lng: 11.582 },
    oneLiner: 'Beer hall lunches, alpine day trips, autumn fairs that take over the city.',
    viatorQuery: 'Munich',
  },
  {
    slug: 'vienna',
    name: 'Vienna',
    countryName: 'Austria',
    countryCode: 'AT',
    region: 'europe',
    coordinates: { lat: 48.2082, lng: 16.3738 },
    oneLiner: 'Imperial palaces, coffee houses with newspapers, concerts that start at eight.',
    viatorQuery: 'Vienna',
  },
  {
    slug: 'prague',
    name: 'Prague',
    countryName: 'Czechia',
    countryCode: 'CZ',
    region: 'europe',
    coordinates: { lat: 50.0755, lng: 14.4378 },
    oneLiner: 'Castle terraces, gothic bridges, beer gardens with a river view.',
    viatorQuery: 'Prague',
  },
  {
    slug: 'budapest',
    name: 'Budapest',
    countryName: 'Hungary',
    countryCode: 'HU',
    region: 'europe',
    coordinates: { lat: 47.4979, lng: 19.0402 },
    oneLiner: 'Thermal baths, ruin bars, Danube light on baroque stone.',
    viatorQuery: 'Budapest',
  },
  {
    slug: 'dublin',
    name: 'Dublin',
    countryName: 'Ireland',
    countryCode: 'IE',
    region: 'europe',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    oneLiner: 'Coastal walks, literary pubs, Georgian doorways under low winter sun.',
    viatorQuery: 'Dublin',
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    countryName: 'United Kingdom',
    countryCode: 'GB',
    region: 'europe',
    coordinates: { lat: 55.9533, lng: -3.1883 },
    oneLiner: 'Castle on the rock, closes off the Royal Mile, ridges you can walk before lunch.',
    viatorQuery: 'Edinburgh',
  },
  {
    slug: 'copenhagen',
    name: 'Copenhagen',
    countryName: 'Denmark',
    countryCode: 'DK',
    region: 'europe',
    coordinates: { lat: 55.6761, lng: 12.5683 },
    oneLiner: 'Bicycle bridges, harbour swims, design-forward kitchens that keep the lights low.',
    viatorQuery: 'Copenhagen',
  },
  {
    slug: 'stockholm',
    name: 'Stockholm',
    countryName: 'Sweden',
    countryCode: 'SE',
    region: 'europe',
    coordinates: { lat: 59.3293, lng: 18.0686 },
    oneLiner: 'Archipelago ferries, fika afternoons, summer light that does not stop.',
    viatorQuery: 'Stockholm',
  },
  {
    slug: 'zurich',
    name: 'Zurich',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 47.3769, lng: 8.5417 },
    oneLiner: 'Lake swims, alpine trains, old-town lanes you can cross in fifteen minutes.',
    viatorQuery: 'Zurich',
  },
  {
    slug: 'milan',
    name: 'Milan',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 45.4642, lng: 9.19 },
    oneLiner: 'Aperitivo at seven, duomo at dusk, design districts you walk slowly through.',
    viatorQuery: 'Milan',
  },
  {
    slug: 'naples',
    name: 'Naples',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 40.8518, lng: 14.2681 },
    oneLiner: 'Pizza in the old quarter, Pompeii day trips, espresso every two corners.',
    viatorQuery: 'Naples',
  },
  {
    slug: 'nice',
    name: 'Nice',
    countryName: 'France',
    countryCode: 'FR',
    region: 'europe',
    coordinates: { lat: 43.7102, lng: 7.262 },
    oneLiner: 'Promenade mornings, market lunches, beach light on the Côte d Azur.',
    viatorQuery: 'Nice France',
  },
  {
    slug: 'krakow',
    name: 'Kraków',
    countryName: 'Poland',
    countryCode: 'PL',
    region: 'europe',
    coordinates: { lat: 50.0647, lng: 19.945 },
    oneLiner: 'Old square sunsets, Wawel castle, mountain day trips an hour out of town.',
    viatorQuery: 'Krakow',
  },
  {
    slug: 'dubrovnik',
    name: 'Dubrovnik',
    countryName: 'Croatia',
    countryCode: 'HR',
    region: 'europe',
    coordinates: { lat: 42.6507, lng: 18.0944 },
    oneLiner: 'Walled-city walks, island ferries, sea cliffs the colour of old wine.',
    viatorQuery: 'Dubrovnik',
  },
  {
    slug: 'granada',
    name: 'Granada',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 37.1773, lng: -3.5986 },
    oneLiner: 'Alhambra evenings, tapas-with-every-drink, the Sierra Nevada an hour above.',
    viatorQuery: 'Granada Spain',
  },
  {
    slug: 'porto',
    name: 'Porto',
    countryName: 'Portugal',
    countryCode: 'PT',
    region: 'europe',
    coordinates: { lat: 41.1579, lng: -8.6291 },
    oneLiner: 'River-canyon city, tile-fronted streets, port wine cellars across the bridge.',
    viatorQuery: 'Porto',
  },
  {
    slug: 'bruges',
    name: 'Bruges',
    countryName: 'Belgium',
    countryCode: 'BE',
    region: 'europe',
    coordinates: { lat: 51.2093, lng: 3.2247 },
    oneLiner: 'Canal walks, gothic squares, frites and chocolate, evenings without crowds.',
    viatorQuery: 'Bruges',
  },
  {
    slug: 'salzburg',
    name: 'Salzburg',
    countryName: 'Austria',
    countryCode: 'AT',
    region: 'europe',
    coordinates: { lat: 47.8095, lng: 13.055 },
    oneLiner: 'Baroque squares, alpine day trips, the Sound of Music meadows just out of town.',
    viatorQuery: 'Salzburg',
  },
  {
    slug: 'split',
    name: 'Split',
    countryName: 'Croatia',
    countryCode: 'HR',
    region: 'europe',
    coordinates: { lat: 43.5081, lng: 16.4402 },
    oneLiner: 'Roman palace as a living old town, island ferries every morning, beach swims at lunch.',
    viatorQuery: 'Split Croatia',
  },
  {
    slug: 'helsinki',
    name: 'Helsinki',
    countryName: 'Finland',
    countryCode: 'FI',
    region: 'europe',
    coordinates: { lat: 60.1699, lng: 24.9384 },
    oneLiner: 'Design districts, sauna culture, harbour ferries to Suomenlinna in twenty minutes.',
    viatorQuery: 'Helsinki',
  },
  {
    slug: 'sorrento',
    name: 'Sorrento',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 40.6263, lng: 14.3757 },
    oneLiner: 'Cliffside hotels, limoncello terraces, Amalfi and Capri ferries from the harbour below.',
    viatorQuery: 'Sorrento',
  },
  {
    slug: 'bologna',
    name: 'Bologna',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 44.4949, lng: 11.3426 },
    oneLiner: 'Porticoed lanes, ragù lunches, the kitchen capital of Italy without the crowds.',
    viatorQuery: 'Bologna',
  },
  {
    slug: 'bordeaux',
    name: 'Bordeaux',
    countryName: 'France',
    countryCode: 'FR',
    region: 'europe',
    coordinates: { lat: 44.8378, lng: -0.5792 },
    oneLiner: 'Wine-route afternoons, riverbank promenades, eighteenth-century stone in evening light.',
    viatorQuery: 'Bordeaux',
  },
  {
    slug: 'valencia',
    name: 'Valencia',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 39.4699, lng: -0.3763 },
    oneLiner: 'Paella mornings, futurist architecture in the riverbed park, beach afternoons in walking distance.',
    viatorQuery: 'Valencia Spain',
  },
  {
    slug: 'brussels',
    name: 'Brussels',
    countryName: 'Belgium',
    countryCode: 'BE',
    region: 'europe',
    coordinates: { lat: 50.8503, lng: 4.3517 },
    oneLiner: 'Grand-Place evenings, frites and waffles, beer cellars, easy Eurostar weekends.',
    viatorQuery: 'Brussels',
  },
  {
    slug: 'cinque-terre',
    name: 'Cinque Terre',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 44.1063, lng: 9.7406 },
    oneLiner: 'Five painted villages on a cliff, coastal hikes between them, focaccia eaten in the sun.',
    viatorQuery: 'Cinque Terre',
  },
  {
    slug: 'lake-como',
    name: 'Lake Como',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 45.9842, lng: 9.2598 },
    oneLiner: 'Cypress villas, sunset ferries between villages, the mountains in the mirror.',
    viatorQuery: 'Lake Como',
  },
  {
    slug: 'mykonos',
    name: 'Mykonos',
    countryName: 'Greece',
    countryCode: 'GR',
    region: 'europe',
    coordinates: { lat: 37.4467, lng: 25.3289 },
    oneLiner: 'Whitewashed lanes, windmill sunsets, beach clubs that go until dawn.',
    viatorQuery: 'Mykonos',
  },
  {
    slug: 'crete',
    name: 'Crete',
    countryName: 'Greece',
    countryCode: 'GR',
    region: 'europe',
    coordinates: { lat: 35.2401, lng: 24.8093 },
    oneLiner: 'Minoan ruins, mountain villages, gorge hikes, taverna nights on the sea.',
    viatorQuery: 'Crete',
  },
  {
    slug: 'lucerne',
    name: 'Lucerne',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 47.0502, lng: 8.3093 },
    oneLiner: 'Wooden bridges over a glacial lake, alpine train day trips, swans at sunrise.',
    viatorQuery: 'Lucerne',
  },
  {
    slug: 'lauterbrunnen',
    name: 'Lauterbrunnen',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.5933, lng: 7.9081 },
    oneLiner: 'Seventy-two waterfalls in one alpine valley, cliff villages reached by cable car.',
    viatorQuery: 'Lauterbrunnen',
  },
  {
    slug: 'interlaken',
    name: 'Interlaken',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.6863, lng: 7.8632 },
    oneLiner: 'Adventure-sports hub between two glacial lakes, the Jungfrau over the rooftops.',
    viatorQuery: 'Interlaken',
  },
  {
    slug: 'grindelwald',
    name: 'Grindelwald',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.6244, lng: 8.0419 },
    oneLiner: 'Mountain village under the Eiger north face, cableways to alpine ridges every direction.',
    viatorQuery: 'Grindelwald',
  },
  {
    slug: 'zermatt',
    name: 'Zermatt',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.0207, lng: 7.7491 },
    oneLiner: 'Car-free village under the Matterhorn, glacier paradise above, fondue terraces below.',
    viatorQuery: 'Zermatt',
  },
  {
    slug: 'bern',
    name: 'Bern',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.948, lng: 7.4474 },
    oneLiner: 'UNESCO old town in a river bend, arcaded shopping streets, Aare swims in summer.',
    viatorQuery: 'Bern Switzerland',
  },
  {
    slug: 'geneva',
    name: 'Geneva',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.2044, lng: 6.1432 },
    oneLiner: 'Lakefront diplomacy, Mont Blanc on the horizon, chocolate shops in the old town.',
    viatorQuery: 'Geneva',
  },
  {
    slug: 'basel',
    name: 'Basel',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 47.5596, lng: 7.5886 },
    oneLiner: 'Rhine swims in summer, forty museums, art fairs, three countries within a tram ride.',
    viatorQuery: 'Basel',
  },
  {
    slug: 'st-moritz',
    name: 'St. Moritz',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.4983, lng: 9.8358 },
    oneLiner: 'Engadine luxury ski village, sun-drenched lake afternoons, the Glacier Express terminus.',
    viatorQuery: 'St Moritz',
  },
  {
    slug: 'lugano',
    name: 'Lugano',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.0037, lng: 8.9511 },
    oneLiner: 'Italian-Swiss lake town, palm trees on the promenade, gelato in the piazzas.',
    viatorQuery: 'Lugano',
  },
  {
    slug: 'montreux',
    name: 'Montreux',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.4312, lng: 6.9123 },
    oneLiner: 'Lake-Geneva riviera, the Chillon castle at the water, jazz festival at midsummer.',
    viatorQuery: 'Montreux',
  },
  {
    slug: 'wengen',
    name: 'Wengen',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.6056, lng: 7.9219 },
    oneLiner: 'Car-free cliff village above Lauterbrunnen, Eiger trio on the doorstep, Lauberhorn ski race in January.',
    viatorQuery: 'Wengen',
  },
  {
    slug: 'murren',
    name: 'Mürren',
    countryName: 'Switzerland',
    countryCode: 'CH',
    region: 'europe',
    coordinates: { lat: 46.5594, lng: 7.8919 },
    oneLiner: 'Highest car-free village in Switzerland, Schilthorn cable car, the panorama trail above the cloud line.',
    viatorQuery: 'Murren',
  },
  {
    slug: 'hallstatt',
    name: 'Hallstatt',
    countryName: 'Austria',
    countryCode: 'AT',
    region: 'europe',
    coordinates: { lat: 47.5622, lng: 13.6493 },
    oneLiner: 'Mirror lake village, salt mine tours, the most photographed alpine corner in the Salzkammergut.',
    viatorQuery: 'Hallstatt',
  },
  {
    slug: 'innsbruck',
    name: 'Innsbruck',
    countryName: 'Austria',
    countryCode: 'AT',
    region: 'europe',
    coordinates: { lat: 47.2692, lng: 11.4041 },
    oneLiner: 'Alpine capital with a baroque core, ski lifts from the city centre, Olympic-jump views.',
    viatorQuery: 'Innsbruck',
  },
  {
    slug: 'strasbourg',
    name: 'Strasbourg',
    countryName: 'France',
    countryCode: 'FR',
    region: 'europe',
    coordinates: { lat: 48.5734, lng: 7.7521 },
    oneLiner: 'Half-timbered Petite France, canals through the old town, the world’s grandest Christmas market.',
    viatorQuery: 'Strasbourg',
  },
  {
    slug: 'antwerp',
    name: 'Antwerp',
    countryName: 'Belgium',
    countryCode: 'BE',
    region: 'europe',
    coordinates: { lat: 51.2194, lng: 4.4025 },
    oneLiner: 'Diamond district, baroque cathedrals, Rubens museums, fashion-forward boutiques.',
    viatorQuery: 'Antwerp',
  },
  {
    slug: 'bergen',
    name: 'Bergen',
    countryName: 'Norway',
    countryCode: 'NO',
    region: 'europe',
    coordinates: { lat: 60.3913, lng: 5.3221 },
    oneLiner: 'Fjord ferries, fish-market lunches, painted wharf houses, mountains in every direction.',
    viatorQuery: 'Bergen',
  },
  {
    slug: 'lake-bled',
    name: 'Lake Bled',
    countryName: 'Slovenia',
    countryCode: 'SI',
    region: 'europe',
    coordinates: { lat: 46.3683, lng: 14.1146 },
    oneLiner: 'Cream-cake afternoons, pletna boats to the island church, alpine trails behind town.',
    viatorQuery: 'Lake Bled',
  },
  {
    slug: 'hamburg',
    name: 'Hamburg',
    countryName: 'Germany',
    countryCode: 'DE',
    region: 'europe',
    coordinates: { lat: 53.5511, lng: 9.9937 },
    oneLiner: 'Port-city promenades, warehouse districts turned art quarters, Reeperbahn nights.',
    viatorQuery: 'Hamburg',
  },
  {
    slug: 'cologne',
    name: 'Cologne',
    countryName: 'Germany',
    countryCode: 'DE',
    region: 'europe',
    coordinates: { lat: 50.9375, lng: 6.9603 },
    oneLiner: 'Gothic cathedral at twilight, Kölsch beer halls, Rhine bridges festooned in love locks.',
    viatorQuery: 'Cologne',
  },
  {
    slug: 'tallinn',
    name: 'Tallinn',
    countryName: 'Estonia',
    countryCode: 'EE',
    region: 'europe',
    coordinates: { lat: 59.437, lng: 24.7536 },
    oneLiner: 'Medieval walls, design districts in old warehouses, the most digital country in Europe.',
    viatorQuery: 'Tallinn',
  },
  {
    slug: 'madeira',
    name: 'Madeira',
    countryName: 'Portugal',
    countryCode: 'PT',
    region: 'europe',
    coordinates: { lat: 32.7607, lng: -16.9595 },
    oneLiner: 'Levada walks through laurel forests, cliff-side toboggan rides, Funchal harbour evenings.',
    viatorQuery: 'Madeira',
  },
  {
    slug: 'sintra',
    name: 'Sintra',
    countryName: 'Portugal',
    countryCode: 'PT',
    region: 'europe',
    coordinates: { lat: 38.8029, lng: -9.3817 },
    oneLiner: 'Fairy-tale palaces, mist-laced gardens, day-trip from Lisbon with a coastline beyond.',
    viatorQuery: 'Sintra',
  },
  {
    slug: 'mallorca',
    name: 'Mallorca',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 39.6953, lng: 3.0176 },
    oneLiner: 'Tramuntana mountain villages, hidden cove beaches, Palma cathedral above the harbour.',
    viatorQuery: 'Mallorca',
  },
  {
    slug: 'ibiza',
    name: 'Ibiza',
    countryName: 'Spain',
    countryCode: 'ES',
    region: 'europe',
    coordinates: { lat: 38.9067, lng: 1.4206 },
    oneLiner: 'Beach-club mornings, fortified old town evenings, hippie-market afternoons in the north.',
    viatorQuery: 'Ibiza',
  },
  {
    slug: 'marseille',
    name: 'Marseille',
    countryName: 'France',
    countryCode: 'FR',
    region: 'europe',
    coordinates: { lat: 43.2965, lng: 5.3698 },
    oneLiner: 'Mediterranean port-city light, calanque cliff swims, bouillabaisse on the old harbour.',
    viatorQuery: 'Marseille',
  },
  {
    slug: 'lyon',
    name: 'Lyon',
    countryName: 'France',
    countryCode: 'FR',
    region: 'europe',
    coordinates: { lat: 45.764, lng: 4.8357 },
    oneLiner: 'Bouchon dinners, two-river old town, the gastronomic centre of France.',
    viatorQuery: 'Lyon',
  },
  {
    slug: 'palermo',
    name: 'Palermo',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 38.1157, lng: 13.3615 },
    oneLiner: 'Norman cathedrals, street-food markets, baroque churches above the African-tinged sea.',
    viatorQuery: 'Palermo',
  },
  {
    slug: 'verona',
    name: 'Verona',
    countryName: 'Italy',
    countryCode: 'IT',
    region: 'europe',
    coordinates: { lat: 45.4384, lng: 10.9916 },
    oneLiner: 'Roman arena opera nights, Juliet’s balcony, Valpolicella wine afternoons.',
    viatorQuery: 'Verona',
  },

  // Americas
  {
    slug: 'new-york',
    name: 'New York',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 40.7128, lng: -74.006 },
    oneLiner: 'Bagels, rooftops, comedy clubs, and the most walkable noise on earth.',
    viatorQuery: 'New York',
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    oneLiner: 'Beach mornings, canyon hikes, sun-warm dinners on patios.',
    viatorQuery: 'Los Angeles',
  },
  {
    slug: 'miami',
    name: 'Miami',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    oneLiner: 'Ocean drive, cafecito mornings, late dinners in Wynwood.',
    viatorQuery: 'Miami',
  },
  {
    slug: 'cancun',
    name: 'Cancún',
    countryName: 'Mexico',
    countryCode: 'MX',
    region: 'americas',
    coordinates: { lat: 21.1619, lng: -86.8515 },
    oneLiner: 'Cenote swims, Mayan ruins, beach days that never end too early.',
    viatorQuery: 'Cancun',
  },
  {
    slug: 'tulum',
    name: 'Tulum',
    countryName: 'Mexico',
    countryCode: 'MX',
    region: 'americas',
    coordinates: { lat: 20.2114, lng: -87.4654 },
    oneLiner: 'Jungle ruins, cenote afternoons, beachfront kitchens at dusk.',
    viatorQuery: 'Tulum',
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    oneLiner: 'Bridge fog, cable cars, hill-top neighborhoods that you walk all morning to find.',
    viatorQuery: 'San Francisco',
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 41.8781, lng: -87.6298 },
    oneLiner: 'Lakefront runs, deep-dish lunches, river architecture cruises at golden hour.',
    viatorQuery: 'Chicago',
  },
  {
    slug: 'las-vegas',
    name: 'Las Vegas',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 36.1699, lng: -115.1398 },
    oneLiner: 'Show nights, canyon day trips, neon strips that never go fully dark.',
    viatorQuery: 'Las Vegas',
  },
  {
    slug: 'orlando',
    name: 'Orlando',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 28.5383, lng: -81.3792 },
    oneLiner: 'Theme park mornings, lake afternoons, dinner shows for any age.',
    viatorQuery: 'Orlando',
  },
  {
    slug: 'new-orleans',
    name: 'New Orleans',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 29.9511, lng: -90.0715 },
    oneLiner: 'Beignet mornings, jazz clubs at night, river boats that keep their own time.',
    viatorQuery: 'New Orleans',
  },
  {
    slug: 'toronto',
    name: 'Toronto',
    countryName: 'Canada',
    countryCode: 'CA',
    region: 'americas',
    coordinates: { lat: 43.6532, lng: -79.3832 },
    oneLiner: 'Lake walks, multicultural markets, tower views that go all the way to Buffalo.',
    viatorQuery: 'Toronto',
  },
  {
    slug: 'vancouver',
    name: 'Vancouver',
    countryName: 'Canada',
    countryCode: 'CA',
    region: 'americas',
    coordinates: { lat: 49.2827, lng: -123.1207 },
    oneLiner: 'Forest in the city, snow above the skyline, ocean every direction you walk.',
    viatorQuery: 'Vancouver',
  },
  {
    slug: 'montreal',
    name: 'Montréal',
    countryName: 'Canada',
    countryCode: 'CA',
    region: 'americas',
    coordinates: { lat: 45.5017, lng: -73.5673 },
    oneLiner: 'Bagel mornings, mountain park afternoons, French-tinged nights in the Plateau.',
    viatorQuery: 'Montreal',
  },
  {
    slug: 'mexico-city',
    name: 'Mexico City',
    countryName: 'Mexico',
    countryCode: 'MX',
    region: 'americas',
    coordinates: { lat: 19.4326, lng: -99.1332 },
    oneLiner: 'Taco lunches, art-deco neighborhoods, pyramid day trips that change the scale of things.',
    viatorQuery: 'Mexico City',
  },
  {
    slug: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    countryName: 'Brazil',
    countryCode: 'BR',
    region: 'americas',
    coordinates: { lat: -22.9068, lng: -43.1729 },
    oneLiner: 'Beach mornings, mountain cable cars, samba nights below Sugarloaf.',
    viatorQuery: 'Rio de Janeiro',
  },
  {
    slug: 'buenos-aires',
    name: 'Buenos Aires',
    countryName: 'Argentina',
    countryCode: 'AR',
    region: 'americas',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    oneLiner: 'Parrilla dinners, tango halls, leafy avenues with European bones.',
    viatorQuery: 'Buenos Aires',
  },
  {
    slug: 'lima',
    name: 'Lima',
    countryName: 'Peru',
    countryCode: 'PE',
    region: 'americas',
    coordinates: { lat: -12.0464, lng: -77.0428 },
    oneLiner: 'Ceviche lunches, cliff-top walks, a kitchen scene that earns every headline.',
    viatorQuery: 'Lima Peru',
  },
  {
    slug: 'cusco',
    name: 'Cusco',
    countryName: 'Peru',
    countryCode: 'PE',
    region: 'americas',
    coordinates: { lat: -13.5319, lng: -71.9675 },
    oneLiner: 'Inca stone in the streets, sacred valley day trips, Machu Picchu within reach.',
    viatorQuery: 'Cusco',
  },
  {
    slug: 'cartagena',
    name: 'Cartagena',
    countryName: 'Colombia',
    countryCode: 'CO',
    region: 'americas',
    coordinates: { lat: 10.3997, lng: -75.5144 },
    oneLiner: 'Walled-city evenings, salsa terraces, island ferries to clear-water beaches.',
    viatorQuery: 'Cartagena',
  },
  {
    slug: 'boston',
    name: 'Boston',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 42.3601, lng: -71.0589 },
    oneLiner: 'Freedom Trail walks, harbor seafood, college-town autumn light on brick.',
    viatorQuery: 'Boston',
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 47.6062, lng: -122.3321 },
    oneLiner: 'Market mornings, ferry rides, mountain ridges above the puget sound.',
    viatorQuery: 'Seattle',
  },
  {
    slug: 'washington-dc',
    name: 'Washington, D.C.',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 38.9072, lng: -77.0369 },
    oneLiner: 'Free museums, monumental walks, cherry blossom evenings along the tidal basin.',
    viatorQuery: 'Washington DC',
  },
  {
    slug: 'quebec-city',
    name: 'Quebec City',
    countryName: 'Canada',
    countryCode: 'CA',
    region: 'americas',
    coordinates: { lat: 46.8139, lng: -71.208 },
    oneLiner: 'Walled old town, French bakeries, winter carnivals and summer river light.',
    viatorQuery: 'Quebec City',
  },
  {
    slug: 'oaxaca',
    name: 'Oaxaca',
    countryName: 'Mexico',
    countryCode: 'MX',
    region: 'americas',
    coordinates: { lat: 17.0732, lng: -96.7266 },
    oneLiner: 'Mezcal palenques, mole markets, mountain ruins above the colonial centre.',
    viatorQuery: 'Oaxaca',
  },
  {
    slug: 'medellin',
    name: 'Medellín',
    countryName: 'Colombia',
    countryCode: 'CO',
    region: 'americas',
    coordinates: { lat: 6.2442, lng: -75.5812 },
    oneLiner: 'Cable cars to hillside neighborhoods, spring weather year-round, kitchens with a new generation.',
    viatorQuery: 'Medellin',
  },
  {
    slug: 'honolulu',
    name: 'Honolulu',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 21.3069, lng: -157.8583 },
    oneLiner: 'Waikiki sunrises, Diamond Head climbs, plate-lunch trucks, snorkel mornings at Hanauma Bay.',
    viatorQuery: 'Honolulu',
  },
  {
    slug: 'maui',
    name: 'Maui',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 20.7984, lng: -156.3319 },
    oneLiner: 'Road-to-Hana waterfalls, Haleakala summit dawns, beach mornings on the windward coast.',
    viatorQuery: 'Maui',
  },
  {
    slug: 'nashville',
    name: 'Nashville',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 36.1627, lng: -86.7816 },
    oneLiner: 'Honky-tonk Broadway nights, hot chicken lunches, Music Row recording-studio history.',
    viatorQuery: 'Nashville',
  },
  {
    slug: 'austin',
    name: 'Austin',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 30.2672, lng: -97.7431 },
    oneLiner: 'BBQ trailers, lake swims at Barton Springs, live-music venues every block of Sixth Street.',
    viatorQuery: 'Austin',
  },
  {
    slug: 'banff',
    name: 'Banff',
    countryName: 'Canada',
    countryCode: 'CA',
    region: 'americas',
    coordinates: { lat: 51.1784, lng: -115.5708 },
    oneLiner: 'Glacial lakes, alpine trails, hot springs, the most photographed mountains in North America.',
    viatorQuery: 'Banff',
  },
  {
    slug: 'charleston',
    name: 'Charleston',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 32.7765, lng: -79.9311 },
    oneLiner: 'Pastel rowhouses, harbor sunsets, low-country kitchens, antebellum gardens.',
    viatorQuery: 'Charleston SC',
  },
  {
    slug: 'savannah',
    name: 'Savannah',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 32.0809, lng: -81.0912 },
    oneLiner: 'Spanish-moss squares, riverfront cobblestones, southern food, ghost-story tours after dark.',
    viatorQuery: 'Savannah',
  },
  {
    slug: 'denver',
    name: 'Denver',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 39.7392, lng: -104.9903 },
    oneLiner: 'Mile-high city, Rocky Mountain gateway, craft brewery scene, sun-baked plains light.',
    viatorQuery: 'Denver',
  },
  {
    slug: 'san-diego',
    name: 'San Diego',
    countryName: 'United States',
    countryCode: 'US',
    region: 'americas',
    coordinates: { lat: 32.7157, lng: -117.1611 },
    oneLiner: 'Pacific beaches, Balboa Park museums, fish tacos, year-round mild light.',
    viatorQuery: 'San Diego',
  },
  {
    slug: 'whistler',
    name: 'Whistler',
    countryName: 'Canada',
    countryCode: 'CA',
    region: 'americas',
    coordinates: { lat: 50.1163, lng: -122.9574 },
    oneLiner: 'Two mountains, the world’s longest gondola, summer trails, winter powder.',
    viatorQuery: 'Whistler',
  },
  {
    slug: 'santiago',
    name: 'Santiago',
    countryName: 'Chile',
    countryCode: 'CL',
    region: 'americas',
    coordinates: { lat: -33.4489, lng: -70.6693 },
    oneLiner: 'Andes peaks behind the skyline, vineyard day trips, coastal Valparaíso a short bus away.',
    viatorQuery: 'Santiago Chile',
  },
  {
    slug: 'quito',
    name: 'Quito',
    countryName: 'Ecuador',
    countryCode: 'EC',
    region: 'americas',
    coordinates: { lat: -0.1807, lng: -78.4678 },
    oneLiner: 'UNESCO colonial centre at 2,850 m, the equator monument, Galápagos flights from the airport.',
    viatorQuery: 'Quito',
  },

  // MENA + Africa
  {
    slug: 'dubai',
    name: 'Dubai',
    countryName: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'mena',
    coordinates: { lat: 25.2048, lng: 55.2708 },
    oneLiner: 'Desert sunrise, marina nights, towers that catch the gold light.',
    viatorQuery: 'Dubai',
  },
  {
    slug: 'marrakech',
    name: 'Marrakech',
    countryName: 'Morocco',
    countryCode: 'MA',
    region: 'mena',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    oneLiner: 'Souk mornings, riad afternoons, drum circles on the square at dusk.',
    viatorQuery: 'Marrakech',
  },
  {
    slug: 'cape-town',
    name: 'Cape Town',
    countryName: 'South Africa',
    countryCode: 'ZA',
    region: 'africa',
    coordinates: { lat: -33.9249, lng: 18.4241 },
    oneLiner: 'Table Mountain hikes, wine farm afternoons, ocean light at the Cape.',
    viatorQuery: 'Cape Town',
  },
  {
    slug: 'cairo',
    name: 'Cairo',
    countryName: 'Egypt',
    countryCode: 'EG',
    region: 'mena',
    coordinates: { lat: 30.0444, lng: 31.2357 },
    oneLiner: 'Pyramids at sunrise, Nile evenings, market lanes that feel a thousand years deep.',
    viatorQuery: 'Cairo',
  },
  {
    slug: 'petra',
    name: 'Petra',
    countryName: 'Jordan',
    countryCode: 'JO',
    region: 'mena',
    coordinates: { lat: 30.3285, lng: 35.4444 },
    oneLiner: 'Rose-red canyons, candlelit treasury nights, desert silence at the rim.',
    viatorQuery: 'Petra',
  },
  {
    slug: 'tel-aviv',
    name: 'Tel Aviv',
    countryName: 'Israel',
    countryCode: 'IL',
    region: 'mena',
    coordinates: { lat: 32.0853, lng: 34.7818 },
    oneLiner: 'Beach mornings, market lunches, Bauhaus streets and late-night bars.',
    viatorQuery: 'Tel Aviv',
  },
  {
    slug: 'doha',
    name: 'Doha',
    countryName: 'Qatar',
    countryCode: 'QA',
    region: 'mena',
    coordinates: { lat: 25.2854, lng: 51.531 },
    oneLiner: 'Souq evenings, museum mornings, dune day trips an hour past the city.',
    viatorQuery: 'Doha',
  },
  {
    slug: 'abu-dhabi',
    name: 'Abu Dhabi',
    countryName: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'mena',
    coordinates: { lat: 24.4539, lng: 54.3773 },
    oneLiner: 'Grand mosque mornings, mangrove kayaks, desert resort nights beyond the city.',
    viatorQuery: 'Abu Dhabi',
  },
  {
    slug: 'nairobi',
    name: 'Nairobi',
    countryName: 'Kenya',
    countryCode: 'KE',
    region: 'africa',
    coordinates: { lat: -1.2921, lng: 36.8219 },
    oneLiner: 'Safari starts here: park drives at dawn, market lunches, giraffe centre afternoons.',
    viatorQuery: 'Nairobi',
  },
  {
    slug: 'zanzibar',
    name: 'Zanzibar',
    countryName: 'Tanzania',
    countryCode: 'TZ',
    region: 'africa',
    coordinates: { lat: -6.1659, lng: 39.2026 },
    oneLiner: 'Stone Town alleys, spice tours, white-sand beaches that catch the trade winds.',
    viatorQuery: 'Zanzibar',
  },
  {
    slug: 'victoria-falls',
    name: 'Victoria Falls',
    countryName: 'Zambia',
    countryCode: 'ZM',
    region: 'africa',
    coordinates: { lat: -17.9243, lng: 25.8572 },
    oneLiner: 'Mist that you can see from a mile away, gorge swings, river safari sundowners.',
    viatorQuery: 'Victoria Falls',
  },
  {
    slug: 'mauritius',
    name: 'Mauritius',
    countryName: 'Mauritius',
    countryCode: 'MU',
    region: 'africa',
    coordinates: { lat: -20.3484, lng: 57.5522 },
    oneLiner: 'Lagoon snorkels, tea-route afternoons, mountain ridges above the sugar-cane plains.',
    viatorQuery: 'Mauritius',
  },
  {
    slug: 'fes',
    name: 'Fes',
    countryName: 'Morocco',
    countryCode: 'MA',
    region: 'mena',
    coordinates: { lat: 34.0181, lng: -5.0078 },
    oneLiner: 'Medieval medina, leather tanneries, mosaic courtyards, tagines slow-cooked on charcoal.',
    viatorQuery: 'Fes',
  },
  {
    slug: 'amman',
    name: 'Amman',
    countryName: 'Jordan',
    countryCode: 'JO',
    region: 'mena',
    coordinates: { lat: 31.9454, lng: 35.9284 },
    oneLiner: 'Citadel sunsets over hills, Roman theatre, mansaf dinners, the gateway to Petra and the Dead Sea.',
    viatorQuery: 'Amman',
  },
  {
    slug: 'casablanca',
    name: 'Casablanca',
    countryName: 'Morocco',
    countryCode: 'MA',
    region: 'mena',
    coordinates: { lat: 33.5731, lng: -7.5898 },
    oneLiner: 'Atlantic coast city, Hassan II mosque on the waves, art-deco boulevards, port-city lights at night.',
    viatorQuery: 'Casablanca',
  },
  {
    slug: 'chefchaouen',
    name: 'Chefchaouen',
    countryName: 'Morocco',
    countryCode: 'MA',
    region: 'mena',
    coordinates: { lat: 35.1689, lng: -5.2636 },
    oneLiner: 'Blue-washed mountain medina, leather and weaving markets, Rif hill walks above town.',
    viatorQuery: 'Chefchaouen',
  },
  {
    slug: 'luxor',
    name: 'Luxor',
    countryName: 'Egypt',
    countryCode: 'EG',
    region: 'mena',
    coordinates: { lat: 25.6872, lng: 32.6396 },
    oneLiner: 'Karnak at sunrise, Valley of the Kings, balloon rides over the temples, Nile boat afternoons.',
    viatorQuery: 'Luxor',
  },
  {
    slug: 'johannesburg',
    name: 'Johannesburg',
    countryName: 'South Africa',
    countryCode: 'ZA',
    region: 'africa',
    coordinates: { lat: -26.2041, lng: 28.0473 },
    oneLiner: 'Apartheid Museum, Soweto bike tours, Maboneng art district, the Cradle of Humankind nearby.',
    viatorQuery: 'Johannesburg',
  },

  // Oceania
  {
    slug: 'sydney',
    name: 'Sydney',
    countryName: 'Australia',
    countryCode: 'AU',
    region: 'oceania',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    oneLiner: 'Harbour ferries, headland walks, beach mornings, dumpling lunches.',
    viatorQuery: 'Sydney',
  },
  {
    slug: 'melbourne',
    name: 'Melbourne',
    countryName: 'Australia',
    countryCode: 'AU',
    region: 'oceania',
    coordinates: { lat: -37.8136, lng: 144.9631 },
    oneLiner: 'Laneway coffee, gallery afternoons, Great Ocean Road sunsets a day trip away.',
    viatorQuery: 'Melbourne',
  },
  {
    slug: 'auckland',
    name: 'Auckland',
    countryName: 'New Zealand',
    countryCode: 'NZ',
    region: 'oceania',
    coordinates: { lat: -36.8485, lng: 174.7633 },
    oneLiner: 'Harbour sailing, island ferries, vineyards a half-hour past the bridge.',
    viatorQuery: 'Auckland',
  },
  {
    slug: 'queenstown',
    name: 'Queenstown',
    countryName: 'New Zealand',
    countryCode: 'NZ',
    region: 'oceania',
    coordinates: { lat: -45.0312, lng: 168.6626 },
    oneLiner: 'Lake mornings, alpine trails, adrenaline drops at the edge of every ridge.',
    viatorQuery: 'Queenstown',
  },
  {
    slug: 'wellington',
    name: 'Wellington',
    countryName: 'New Zealand',
    countryCode: 'NZ',
    region: 'oceania',
    coordinates: { lat: -41.2865, lng: 174.7762 },
    oneLiner: 'Coffee culture, harbour winds, the Te Papa museum, day-trips into wine country.',
    viatorQuery: 'Wellington',
  },
  {
    slug: 'brisbane',
    name: 'Brisbane',
    countryName: 'Australia',
    countryCode: 'AU',
    region: 'oceania',
    coordinates: { lat: -27.4698, lng: 153.0251 },
    oneLiner: 'River-city walks, Gold Coast day trips, sub-tropical light from May through October.',
    viatorQuery: 'Brisbane',
  },
  {
    slug: 'cairns',
    name: 'Cairns',
    countryName: 'Australia',
    countryCode: 'AU',
    region: 'oceania',
    coordinates: { lat: -16.9203, lng: 145.7781 },
    oneLiner: 'Great Barrier Reef day trips, Daintree rainforest treks, Esplanade lagoon swims.',
    viatorQuery: 'Cairns',
  },

  // ────── Phase 8 expansion: Asia depth + Europe islands + Latin America + India ──────
  {
    slug: 'kanazawa',
    name: 'Kanazawa',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 36.5613, lng: 136.6562 },
    oneLiner: 'Gold-leaf workshops, samurai lanes, and Kenrokuen — one of Japan’s three great gardens.',
    viatorQuery: 'Kanazawa',
  },
  {
    slug: 'fukuoka',
    name: 'Fukuoka',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 33.5904, lng: 130.4017 },
    oneLiner: 'Tonkotsu ramen at the yatai stalls, sunset beaches, and Kyushu food that punches above the city’s size.',
    viatorQuery: 'Fukuoka',
  },
  {
    slug: 'el-nido',
    name: 'El Nido',
    countryName: 'Philippines',
    countryCode: 'PH',
    region: 'asia',
    coordinates: { lat: 11.2, lng: 119.4167 },
    oneLiner: 'Karst cliffs rising from turquoise lagoons — Palawan’s island-hopping capital.',
    viatorQuery: 'El Nido Palawan',
  },
  {
    slug: 'jodhpur',
    name: 'Jodhpur',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 26.2389, lng: 73.0243 },
    oneLiner: 'The Blue City — Mehrangarh Fort towering over indigo lanes and rooftop cafés.',
    viatorQuery: 'Jodhpur',
  },
  {
    slug: 'udaipur',
    name: 'Udaipur',
    countryName: 'India',
    countryCode: 'IN',
    region: 'asia',
    coordinates: { lat: 24.5854, lng: 73.7125 },
    oneLiner: 'Marble palaces on a lake, sunset boat rides, one of India’s most romantic cities.',
    viatorQuery: 'Udaipur',
  },
  {
    slug: 'rhodes',
    name: 'Rhodes',
    countryName: 'Greece',
    countryCode: 'GR',
    region: 'europe',
    coordinates: { lat: 36.4341, lng: 28.2176 },
    oneLiner: 'A medieval old town wrapped in city walls, Aegean beaches, and hilltop acropoli you can climb by scooter.',
    viatorQuery: 'Rhodes',
  },
  {
    slug: 'corfu',
    name: 'Corfu',
    countryName: 'Greece',
    countryCode: 'GR',
    region: 'europe',
    coordinates: { lat: 39.6243, lng: 19.9217 },
    oneLiner: 'Venetian fortresses and Ionian coves — the greenest Greek island.',
    viatorQuery: 'Corfu',
  },
  {
    slug: 'bucharest',
    name: 'Bucharest',
    countryName: 'Romania',
    countryCode: 'RO',
    region: 'europe',
    coordinates: { lat: 44.4268, lng: 26.1025 },
    oneLiner: 'Belle Époque boulevards, communist monoliths, and the launch pad for Transylvania day trips.',
    viatorQuery: 'Bucharest',
  },
  {
    slug: 'panama-city',
    name: 'Panama City',
    countryName: 'Panama',
    countryCode: 'PA',
    region: 'americas',
    coordinates: { lat: 8.9824, lng: -79.5199 },
    oneLiner: 'A modern skyline over Casco Viejo’s cobblestones — and canal locks you can watch from a rooftop bar.',
    viatorQuery: 'Panama City',
  },
  {
    slug: 'havana',
    name: 'Havana',
    countryName: 'Cuba',
    countryCode: 'CU',
    region: 'americas',
    coordinates: { lat: 23.1136, lng: -82.3666 },
    oneLiner: '1950s cars, sea-spray on the Malecón, live son music spilling out of every doorway in Old Havana.',
    viatorQuery: 'Havana',
  },

  // ────── Phase 9 expansion: Japan depth + Oceania islands + Caribbean/Mexico + South America south + MENA Red Sea ──────
  {
    slug: 'nara',
    name: 'Nara',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 34.6851, lng: 135.8048 },
    oneLiner: 'Bowing deer, Tōdai-ji\'s Great Buddha, and a park that turns golden every autumn — an easy day trip from Kyoto.',
    viatorQuery: 'Nara Japan',
  },
  {
    slug: 'hakone',
    name: 'Hakone',
    countryName: 'Japan',
    countryCode: 'JP',
    region: 'asia',
    coordinates: { lat: 35.2325, lng: 139.1067 },
    oneLiner: 'Onsen ryokans with Mount Fuji framed in the window — Japan\'s most beloved hot-spring town.',
    viatorQuery: 'Hakone',
  },
  {
    slug: 'kandy',
    name: 'Kandy',
    countryName: 'Sri Lanka',
    countryCode: 'LK',
    region: 'asia',
    coordinates: { lat: 7.2906, lng: 80.6337 },
    oneLiner: 'Sri Lanka\'s hill-country capital — a sacred lake, the Temple of the Tooth, tea estates in every direction.',
    viatorQuery: 'Kandy Sri Lanka',
  },
  {
    slug: 'bora-bora',
    name: 'Bora Bora',
    countryName: 'French Polynesia',
    countryCode: 'PF',
    region: 'oceania',
    coordinates: { lat: -16.5004, lng: -151.7415 },
    oneLiner: 'Overwater bungalows on a turquoise lagoon with Mount Otemanu rising behind — the honeymoon shorthand.',
    viatorQuery: 'Bora Bora',
  },
  {
    slug: 'nadi',
    name: 'Nadi',
    countryName: 'Fiji',
    countryCode: 'FJ',
    region: 'oceania',
    coordinates: { lat: -17.7765, lng: 177.4356 },
    oneLiner: 'Fiji\'s international gateway — jumping-off point for Yasawa island hops, coral gardens, and the warmest local welcome.',
    viatorQuery: 'Nadi Fiji',
  },
  {
    slug: 'san-juan',
    name: 'San Juan',
    countryName: 'Puerto Rico',
    countryCode: 'PR',
    region: 'americas',
    coordinates: { lat: 18.4655, lng: -66.1057 },
    oneLiner: 'Cobblestone Old San Juan by day, salsa on Ashford Avenue at night — Caribbean without the customs line for US travelers.',
    viatorQuery: 'San Juan Puerto Rico',
  },
  {
    slug: 'playa-del-carmen',
    name: 'Playa del Carmen',
    countryName: 'Mexico',
    countryCode: 'MX',
    region: 'americas',
    coordinates: { lat: 20.6296, lng: -87.0739 },
    oneLiner: 'Quinta Avenida strolls at sunset, cenote day trips, and Fifth Avenue for the tacos — Riviera Maya\'s liveliest town.',
    viatorQuery: 'Playa del Carmen',
  },
  {
    slug: 'cabo-san-lucas',
    name: 'Cabo San Lucas',
    countryName: 'Mexico',
    countryCode: 'MX',
    region: 'americas',
    coordinates: { lat: 22.8905, lng: -109.9167 },
    oneLiner: 'Land\'s End arch, Pacific-meets-Sea-of-Cortez sunsets, and marlin fishing — Baja\'s biggest resort scene.',
    viatorQuery: 'Cabo San Lucas',
  },
  {
    slug: 'ushuaia',
    name: 'Ushuaia',
    countryName: 'Argentina',
    countryCode: 'AR',
    region: 'americas',
    coordinates: { lat: -54.8019, lng: -68.3030 },
    oneLiner: 'The southernmost city on Earth — Beagle Channel cruises, Antarctica departures, and Tierra del Fuego mountains at the door.',
    viatorQuery: 'Ushuaia',
  },
  {
    slug: 'sharm-el-sheikh',
    name: 'Sharm el-Sheikh',
    countryName: 'Egypt',
    countryCode: 'EG',
    region: 'mena',
    coordinates: { lat: 27.9158, lng: 34.3300 },
    oneLiner: 'Red Sea coral reefs steps from your resort, dive boats to Ras Mohammed, and Sinai desert at your back.',
    viatorQuery: 'Sharm el-Sheikh',
  },

  // ────── Phase 10 expansion (first platform-native batch: added once
  // here, shipped by every brand) ──────
  { slug: 'malaga', name: 'Málaga', countryName: 'Spain', countryCode: 'ES', region: 'europe', coordinates: { lat: 36.7213, lng: -4.4213 }, oneLiner: 'Picasso\'s birthplace turned Costa del Sol capital — rooftop bars, beach chiringuitos, and a castle above the port.', viatorQuery: 'Malaga' },
  { slug: 'san-sebastian', name: 'San Sebastián', countryName: 'Spain', countryCode: 'ES', region: 'europe', coordinates: { lat: 43.3183, lng: -1.9812 }, oneLiner: 'La Concha\'s perfect crescent beach and more Michelin stars per capita than almost anywhere on Earth.', viatorQuery: 'San Sebastian' },
  { slug: 'positano', name: 'Positano', countryName: 'Italy', countryCode: 'IT', region: 'europe', coordinates: { lat: 40.6281, lng: 14.4850 }, oneLiner: 'The Amalfi Coast\'s postcard — pastel houses stacked down a cliff to a beach full of striped umbrellas.', viatorQuery: 'Positano' },
  { slug: 'matera', name: 'Matera', countryName: 'Italy', countryCode: 'IT', region: 'europe', coordinates: { lat: 40.6664, lng: 16.6043 }, oneLiner: 'Ancient cave dwellings carved into a ravine — one of the oldest continuously inhabited places on Earth.', viatorQuery: 'Matera' },
  { slug: 'oslo', name: 'Oslo', countryName: 'Norway', countryCode: 'NO', region: 'europe', coordinates: { lat: 59.9139, lng: 10.7522 }, oneLiner: 'Fjord swims off the Opera House roof, Munch and Viking ships, and forests inside the city limits.', viatorQuery: 'Oslo' },
  { slug: 'warsaw', name: 'Warsaw', countryName: 'Poland', countryCode: 'PL', region: 'europe', coordinates: { lat: 52.2297, lng: 21.0122 }, oneLiner: 'A rebuilt Old Town, Chopin in the parks, and Poland\'s best food scene at half Western prices.', viatorQuery: 'Warsaw' },
  { slug: 'okinawa', name: 'Okinawa', countryName: 'Japan', countryCode: 'JP', region: 'asia', coordinates: { lat: 26.2124, lng: 127.6809 }, oneLiner: 'Japan\'s subtropical island chain — coral reefs, Ryukyu castles, and the longevity diet at its source.', viatorQuery: 'Okinawa' },
  { slug: 'jeju', name: 'Jeju', countryName: 'South Korea', countryCode: 'KR', region: 'asia', coordinates: { lat: 33.4996, lng: 126.5312 }, oneLiner: 'Korea\'s honeymoon island — volcanic craters, waterfall hikes, and haenyeo divers bringing up abalone.', viatorQuery: 'Jeju Island' },
  { slug: 'koh-samui', name: 'Koh Samui', countryName: 'Thailand', countryCode: 'TH', region: 'asia', coordinates: { lat: 9.5120, lng: 100.0136 }, oneLiner: 'Palm-fringed beaches, jungle waterfalls, and beach villas — the Gulf of Thailand\'s resort island.', viatorQuery: 'Koh Samui' },
  { slug: 'langkawi', name: 'Langkawi', countryName: 'Malaysia', countryCode: 'MY', region: 'asia', coordinates: { lat: 6.3500, lng: 99.8000 }, oneLiner: 'Duty-free island of 99 isles — sky bridges over rainforest, mangrove boat trips, sunset beach bars.', viatorQuery: 'Langkawi' },
  { slug: 'cebu', name: 'Cebu', countryName: 'Philippines', countryCode: 'PH', region: 'asia', coordinates: { lat: 10.3157, lng: 123.8854 }, oneLiner: 'Whale sharks at dawn, canyoneering to Kawasan Falls, and the gateway to the central Philippines.', viatorQuery: 'Cebu' },
  { slug: 'pokhara', name: 'Pokhara', countryName: 'Nepal', countryCode: 'NP', region: 'asia', coordinates: { lat: 28.2096, lng: 83.9856 }, oneLiner: 'Lakeside basecamp of the Annapurnas — paragliding at sunrise, World Peace Pagoda hikes, trek permits in hand.', viatorQuery: 'Pokhara' },
  { slug: 'varanasi', name: 'Varanasi', countryName: 'India', countryCode: 'IN', region: 'asia', coordinates: { lat: 25.3176, lng: 82.9739 }, oneLiner: 'India\'s holiest city — dawn boat rides past the ghats, evening aarti fires, lanes older than history.', viatorQuery: 'Varanasi' },
  { slug: 'puerto-vallarta', name: 'Puerto Vallarta', countryName: 'Mexico', countryCode: 'MX', region: 'americas', coordinates: { lat: 20.6534, lng: -105.2253 }, oneLiner: 'Pacific sunsets over Banderas Bay — a cobblestone old town, whale season, and Mexico\'s friendliest beach city.', viatorQuery: 'Puerto Vallarta' },
  { slug: 'merida', name: 'Mérida', countryName: 'Mexico', countryCode: 'MX', region: 'americas', coordinates: { lat: 20.9674, lng: -89.5926 }, oneLiner: 'The Yucatán\'s pastel capital — Maya ruins and cenotes in every direction, cochinita pibil on every corner.', viatorQuery: 'Merida Mexico' },
  { slug: 'san-miguel-de-allende', name: 'San Miguel de Allende', countryName: 'Mexico', countryCode: 'MX', region: 'americas', coordinates: { lat: 20.9144, lng: -100.7452 }, oneLiner: 'Cobblestones, a pink parish church, and rooftop margaritas — repeatedly voted the world\'s best small city.', viatorQuery: 'San Miguel de Allende' },
  { slug: 'bogota', name: 'Bogotá', countryName: 'Colombia', countryCode: 'CO', region: 'americas', coordinates: { lat: 4.7110, lng: -74.0721 }, oneLiner: 'Andean capital at 2,600m — gold museums, graffiti tours, and Monserrate towering over La Candelaria.', viatorQuery: 'Bogota' },
  { slug: 'muscat', name: 'Muscat', countryName: 'Oman', countryCode: 'OM', region: 'mena', coordinates: { lat: 23.5880, lng: 58.3829 }, oneLiner: 'The Gulf\'s understated gem — a grand mosque, wadi swims, and dhows under forts at sunset.', viatorQuery: 'Muscat' },
  { slug: 'perth', name: 'Perth', countryName: 'Australia', countryCode: 'AU', region: 'oceania', coordinates: { lat: -31.9505, lng: 115.8605 }, oneLiner: 'The world\'s most remote big city — Indian Ocean beaches, quokkas on Rottnest, wineries up the Swan Valley.', viatorQuery: 'Perth' },
  { slug: 'gold-coast', name: 'Gold Coast', countryName: 'Australia', countryCode: 'AU', region: 'oceania', coordinates: { lat: -28.0167, lng: 153.4000 }, oneLiner: '57km of surf beaches backed by theme parks and rainforest hinterland — Australia\'s playground.', viatorQuery: 'Gold Coast' },
];

/** Allowed itinerary durations (days). */
export const SEO_ITINERARY_DAYS: readonly number[] = [2, 3, 4, 5, 7];

/** Lookup helpers. */
export function findCityBySlug(slug: string): SeoCity | null {
  return SEO_CITIES.find((c) => c.slug === slug) ?? null;
}

export function isValidItineraryDays(n: number): boolean {
  return SEO_ITINERARY_DAYS.includes(n);
}

/** Group cities by region — used by the SEO link footer. */
export function citiesByRegion(): Record<SeoCity['region'], SeoCity[]> {
  const out: Record<SeoCity['region'], SeoCity[]> = {
    asia: [],
    europe: [],
    americas: [],
    mena: [],
    oceania: [],
    africa: [],
  };
  for (const c of SEO_CITIES) {
    out[c.region].push(c);
  }
  return out;
}
